### ISSUE TITLE
Adam optimizer missing one required argument

### ISSUE THREAD

**Issue by danif93** [pralab/secml#8]
(Summarize the bug encountered concisely)
> Instantiation of AdamOptimizer in fb_cw_attack.py is missing one required argument ('stepsize').

### Steps to reproduce
> Sequential run of the '15-Foolbox.ipynb' notebook

### [optional] Relevant logs, screenshots, CI/CD tests
![Screenshot 2022-06-29 at 11 56 48](https://user-images.githubusercontent.com/28817248/176418394-bcde9093-3351-4e40-8ef6-38a806e15030.png)

**Comment by maurapintor** [comment]
Hi @danif93, thank you for letting us know! We identified the problem, and we will provide a fix soon.
The error is caused by an update from the foolbox library, that caused a conflict in secml. We will take care of this in the next few days.

**Comment by maurapintor** [comment]
The problem should be solved with the new version. Please, update to v0.15.2!
